const PROJECT = '/dis-web';

const API = `${PROJECT}/rest/api/v1`;

export default {
  name: '智汇数据集成平台',
  prefix: '智汇数据集成平台',
  footerText: 'Copyright © 2018 智汇健康 浙ICP备16002593号',
  iconFontCSS: '/iconfont.css',
  iconFontJS: '/iconfont.js',
  CORS: [],
  PROJECT,
  API,
  version: '1.0',
  jgPrefixPath: 'jg',
  openPages: ['/', '/login'],
  withOutContentPages: [],
  withOutHeaderPages: [],
  withOutMenuPages: [],
  apiPrefix: '/rest/api/v1',
  PUBLIC_KEY:
    'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDeRpWKXx1Drs3veBe53ZaR2GdxqVVMaqxVqECRSCjDwKxQYdEdKw3ys3/diJZLPrlJP272Agw/h5m2EC5XTWe9+f5deKvXEDYx8ercEPYR+ZYHAVNwFpzRbdJcrZUZpD+XG24ZNFAK2MfI8bFXgubYTJxnrU8N1OEC301zHoOSJQIDAQAB',
  pageSize: 20,
  api: {
    // 基本接口
    GET_CONFIG: `${API}/config`,
    USER_LOGIN: `${API}/login`,
    USER_LOGOUT: `${API}/user/logout`,
    USER_CHECK_LOGIN: `${API}/user/isLogin`,
    MODIFY_USER_MIMA: `${API}/login/mima`,
    // dashboard
    GET_GAIYAO_PLATFORM: `${API}/baobiao/platform/gaiyao`,
    GET_SHEBEI_PLATFORM: `${API}/baobiao/platform/shebei`,
    GET_JIANCESHUJU_PLATFORM: `${API}/baobiao/platform/jianceshuju`,
    // group
    GET_GROUP_CHAXUN: `${API}/jigou`,
    GET_GROUP_ALLJIGOU: `${API}/all/jigou`,
    GET_GROUP_BIANJI: `${API}/jigou/:id`,
    DELETE_GROUP_LIST: `${API}/jigou/:id`,
    // 监测数据
    GET_JIANCESHUJI_CHUANG: `${API}/jianceshuju/chuang`,
    GET_JIANCESHUJI_CHUANGDIAN: `${API}/jianceshuju/chuangdian`,
    GET_JIANCESHUJI_DUOTIZHENG: `${API}/jianceshuju/duotizheng`,
    GET_JIANCESHUJI_ZHIHUIXIE: `${API}/jianceshuju/xie`,
    GET_CHUANG_DETAIL: `${API}/jianceshuju/chuang/:bianhao`,
    GET_CHUANGDIAN_DETAIL: `${API}/jianceshuju/chuangdian/:bianhao`,
    GET_DUOTIZHENG_DETAIL: `${API}/jianceshuju/duotizheng/:bianhao`,
    GET_ZHIHUIXIE_DETAIL: `${API}/jianceshuju/xie/:bianhao`,
    DAOCHU_CHUANG_LIST: `${API}/jianceshuju/chuang/daochu/list`,
    DAOCHU_CHUANGDIAN_LIST: `${API}/jianceshuju/chuangdian/daochu/list`,
    DAOCHU_DUOTIZHENG_LIST: `${API}/jianceshuju/duotizheng/daochu/list`,
    DAOCHU_ZHIHUIXIE_LIST: `${API}/jianceshuju/xie/daochu/list`,
    // 采集
    GET_SHEBEI_CAIJISHUJU: `${API}/caijijiance/shebei`,
    GET_JIGOU_CAIJISHUJU: `${API}/caijijiance/jigou`,
    DAOCHU_JIGOU_CAIJISHUJU: `${API}/caijijiance/jigou/daochu`,
    // 异常
    GET_YICHANG_YICHANGSHUJU: `${API}/yichangjilu`,
    // 档案
    GET_DANGAN: `${API}/suoyin`,
    GET_DANGANDETAIL: `${API}/suoyin/:jigou_:id`,
    GET_SHISHI_ZNC: `${API}/suoyin/:jigou_:suoyin/shebei/chuang/shishi`,
    GET_SHUIMIAN_ZNC: `${API}/suoyin/:jigou_:suoyin/shebei/chuang/shuimian`,
    GET_ZAILICHUANG_ZNC: `${API}/suoyin/:jigou_:suoyin/shebei/chuang/zailichuang`,
    GET_LISHI_ZNC: `${API}/suoyin/:jigou_:suoyin/shebei/chuang/lishi`,
    GET_SHISHI_ZNCD: `${API}/suoyin/:jigou_:suoyin/shebei/chuangdian/shishi`,
    GET_SHUIMIAN_ZNCD: `${API}/suoyin/:jigou_:suoyin/shebei/chuangdian/shuimian`,
    GET_ZAILICHUANG_ZNCD: `${API}/suoyin/:jigou_:suoyin/shebei/chuangdian/zailichuang`,
    GET_LISHI_ZNCD: `${API}/suoyin/:jigou_:suoyin/shebei/chuangdian/lishi`,
    GET_ZUIJIN_DTZ: `${API}/suoyin/:jigou_:suoyin/shebei/duotizheng/zuijin`,
    GET_JIBEN_ZHX: `${API}/suoyin/:jigou_:suoyin/shebei/xie/jiben`,
    GET_DINGWEI_ZHX: `${API}/suoyin/:jigou_:suoyin/shebei/xie/dingwei`,
    GET_TISHI_ZHX: `${API}/suoyin/:jigou_:suoyin/shebei/xie/yichangjilu`,
    GET_LISHIBIAODAN_DTZ: `${API}/suoyin/:jigou_:suoyin/shebei/duotizheng/lishibiaodan`,
    GET_LISHITUBIAO_DTZ: `${API}/suoyin/:jigou_:suoyin/shebei/duotizheng/lishitubiao`,
    GET_RUZHU_DETAIL: `${API}/suoyin/:jigou_:suoyin`,
    GET_MUBAN: `${API}/muban/:leixing`,
    GET_MUBAN_DATA: `${API}/suoyin/:jigou_:suoyin/wendang`,
    GET_MUBAN_DATA_ID: `${API}/suoyin/:jigou_:suoyin/wendang/:id`,
    // 用户
    GET_USER_CHAXUN: `${API}/user`,
    GET_USER_NAME: `${API}/user/:id`,
    GET_USERLIST_ZHUANGTAI: `${API}/user/:id/zhuangtai`,
    GET_USERLIST_ROLE: `${API}/user/:id/role`,
    GET_USER_CHONGZHIMIMA: `${API}/user/:id/mima`,
    // 角色
    GET_ROLE_CHAXUN: `${API}/role`,
    GET_ALL_ROLE: `${API}/all/role`,
    GET_ROLE_NAME: `${API}/role/:id`,
    GET_ROLECHAXUN_PRIV: `${API}/priv`,
    // 设备管理
    GET_SHEBEI_LIST: `${API}/shebei`,
    GET_SHEBEI_XIUGAI: `${API}/shebei/:leixing_:bianhao`,
    GET_SHEBEI_DAORU: `${API}/shebei/daoru`,
    GET_SHEBEI_ZNC: `${API}/shebei/chuang/:bianhao`,
    GET_SHEBEI_ZNCSS: `${API}/shebei/chuang/:bianhao/shishi`,
    GET_SHEBEI_ZNCBD: `${API}/shebei/chuang/:bianhao/bangdingjilu`,
    GET_SHEBEI_ZNCD: `${API}/shebei/chuangdian/:bianhao`,
    GET_SHEBEI_ZNCDSS: `${API}/shebei/chuangdian/:bianhao/shishi`,
    GET_SHEBEI_ZNCDBD: `${API}/shebei/chuangdian/:bianhao/bangdingjilu`,
    GET_SHEBEI_DTZ: `${API}/shebei/duotizheng/:bianhao`,
    GET_SHEBEI_DTZBD: `${API}/shebei/duotizheng/:bianhao/bangdingjilu`,
    GET_SHEBEI_ZHXBD: `${API}/shebei/xie/:bianhao/bangdingjilu`,
    GET_DAORU_TEMPLATE: `${API}/shebei/daoru/template`,
    DELETE_DAORU_LIST: `${API}/shebei/daoru/:daoruId`,
    // 提醒管理
    GET_TIXING_LIST: `${API}/yichangjilu`,
  },
};
